### ISSUE TITLE
use-package and :after keyword

### ISSUE THREAD

**Issue by dandrake** [kickingvegas/casual-re-builder#15]
Related to [this casual ibuffer issue](https://github.com/kickingvegas/casual-ibuffer/issues/16), it seems the `use-package` keyword `:after` can be used for those who want to only use `use-package`:

    (use-package re-builder
      :defer t)
    
    (use-package casual-re-builder
      :ensure t
      :defer t
      :bind (:map reb-mode-map
                  ("C-o" . casual-re-builder-tmenu))
      :after (re-builder))

https://www.gnu.org/software/emacs/manual/html_node/use-package/Loading-sequentially.html

That correctly maps `C-o` on my system (emacs 29 on Windows 11).

**Comment by kickingvegas** [comment]
@dandrake Thanks for this configuration info! Will update the docs!
